name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          version: 0.11.3
          version-file: "pyproject.toml"
      - name: Sync enviroment
        run: uv sync --dev
      - name: Run tests
        env:
          CAPTCHALY_APIKEY: ${{ secrets.CAPTCHALY_APIKEY }}
        run: uv run pytest
